//
//  board-archive-utilities.swift
//  ElCanari
//
//  Created by Pierre Molinaro on 17/04/2023.
//
//——————————————————————————————————————————————————————————————————————————————————————————————————

import Foundation

//——————————————————————————————————————————————————————————————————————————————————————————————————
// Version 3 : january 8, 2024
//   - added ARCHIVE_FRONT_TRACKS_WITH_NO_SILK_SCREEN_KEY
//   - added ARCHIVE_Back_TRACKS_WITH_NO_SILK_SCREEN_KEY

let MERGER_ARCHIVE_VERSION = 3

//——————————————————————————————————————————————————————————————————————————————————————————————————

let ARCHIVE_ARTWORK_KEY = "ARTWORK"

let ARCHIVE_BOARD_HEIGHT_KEY          = "BOARD-HEIGHT"
let ARCHIVE_BOARD_HEIGHT_UNIT_KEY     = "BOARD-HEIGHT-UNIT"
let ARCHIVE_BOARD_LINE_WIDTH_KEY      = "BOARD-LINE-WIDTH"
let ARCHIVE_BOARD_LINE_WIDTH_UNIT_KEY = "BOARD-LINE-WIDTH-UNIT"
let ARCHIVE_BOARD_WIDTH_KEY           = "BOARD-WIDTH"
let ARCHIVE_BOARD_WIDTH_UNIT_KEY      = "BOARD-WIDTH-UNIT"

let ARCHIVE_COMPONENT_NAMES_BACK_KEY  = "COMPONENT-NAMES-BACK"
let ARCHIVE_COMPONENT_NAMES_FRONT_KEY = "COMPONENT-NAMES-FRONT"

let ARCHIVE_COMPONENT_VALUES_BACK_KEY  = "COMPONENT-VALUES-BACK"
let ARCHIVE_COMPONENT_VALUES_FRONT_KEY = "COMPONENT-VALUES-FRONT"

let ARCHIVE_DRILLS_KEY = "DRILLS"

let ARCHIVE_IMAGES_LEGEND_BACK_KEY  = "IMAGES-LEGEND-BACK"
let ARCHIVE_IMAGES_LEGEND_FRONT_KEY = "IMAGES-LEGEND-FRONT"

let ARCHIVE_INTERNAL_BOARDS_LIMITS_KEY = "INTERNAL-BOARDS-LIMITS"

let ARCHIVE_LINES_BACK_KEY  = "LINES-BACK"
let ARCHIVE_LINES_FRONT_KEY = "LINES-FRONT"

let ARCHIVE_PACKAGES_BACK_KEY  = "PACKAGES-BACK"
let ARCHIVE_PACKAGES_FRONT_KEY = "PACKAGES-FRONT"

let ARCHIVE_PADS_BACK_KEY       = "PADS-BACK"
let ARCHIVE_PADS_FRONT_KEY      = "PADS-FRONT"
let ARCHIVE_PADS_TRAVERSING_KEY = "PADS-TRAVERSING"

let ARCHIVE_QRCODES_LEGEND_BACK_KEY  = "QRCODES-LEGEND-BACK"
let ARCHIVE_QRCODES_LEGEND_FRONT_KEY = "QRCODES-LEGEND-FRONT"

let ARCHIVE_TEXTS_LAYOUT_BACK_KEY  = "TEXTS-LAYOUT-BACK"
let ARCHIVE_TEXTS_LAYOUT_FRONT_KEY = "TEXTS-LAYOUT-FRONT"
let ARCHIVE_TEXTS_LEGEND_BACK_KEY  = "TEXTS-LEGEND-BACK"
let ARCHIVE_TEXTS_LEGEND_FRONT_KEY = "TEXTS-LEGEND-FRONT"

let ARCHIVE_TRACKS_BACK_KEY   = "TRACKS-BACK"
let ARCHIVE_TRACKS_FRONT_KEY  = "TRACKS-FRONT"
let ARCHIVE_TRACKS_INNER1_KEY = "TRACKS-INNER1"
let ARCHIVE_TRACKS_INNER2_KEY = "TRACKS-INNER2"
let ARCHIVE_TRACKS_INNER3_KEY = "TRACKS-INNER3"
let ARCHIVE_TRACKS_INNER4_KEY = "TRACKS-INNER4"

let ARCHIVE_FRONT_TRACKS_WITH_NO_SILK_SCREEN_KEY = "TRACK-FRONT-NO-SILKSCREEN"
let ARCHIVE_BACK_TRACKS_WITH_NO_SILK_SCREEN_KEY  = "TRACK-BACK-NO-SILKSCREEN"

let ARCHIVE_VERSION_KEY = "ARCHIVE-VERSION"

let ARCHIVE_VIAS_KEY = "VIAS"

//——————————————————————————————————————————————————————————————————————————————————————————————————
