//--- START OF USER ZONE 1


//--- END OF USER ZONE 1
//--------------------------------------------------------------------------------------------------
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//--------------------------------------------------------------------------------------------------

import AppKit

//--------------------------------------------------------------------------------------------------

extension AutoLayoutProjectDocument {
  @objc func performERCCheckingAction (_ inSender : NSObject?) {
//--- START OF USER ZONE 2
    let ok = self.performERCChecking ()
    if !ok, self.rootObject.mBoardSelectedInspector != 4, let window = self.windowForSheet {
      let alert = NSAlert ()
      _ = alert.addButton (withTitle: "Close")
      _ = alert.addButton (withTitle: "Select ERC Inspector")
      alert.messageText =  "ERC Checking error."
      alert.informativeText = "ERC checking has detected error(s)."
      alert.beginSheetModal (for: window) { (response : NSApplication.ModalResponse) in
        if response == .alertSecondButtonReturn {
          self.rootObject.mBoardSelectedInspector = 4
        }
      }
    }
//--- END OF USER ZONE 2
  }
}

//--------------------------------------------------------------------------------------------------
