//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Cocoa

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

func transient_PackageGuide_objectDisplay (
       _ self_x1 : Int,                    
       _ self_y1 : Int,                    
       _ self_x2 : Int,                    
       _ self_y2 : Int
) -> EBShape {
//--- START OF USER ZONE 2
  var bp = EBBezierPath ()
  bp.move (to: CGPoint (x: canariUnitToCocoa (self_x1), y: canariUnitToCocoa (self_y1)))
  bp.line (to: CGPoint (x: canariUnitToCocoa (self_x2), y: canariUnitToCocoa (self_y2)))
  bp.lineWidth = 0.5
  bp.lineCapStyle = .round
  return EBStrokeBezierPathShape ([bp], NSColor.yellow)
//--- END OF USER ZONE 2
}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
