//--------------------------------------------------------------------------------------------------
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//--------------------------------------------------------------------------------------------------

import AppKit
import CanariGeometry

//--------------------------------------------------------------------------------------------------

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//--------------------------------------------------------------------------------------------------

@MainActor func transient_SymbolBezierCurve_strokeBezierPath (
       _ self_x1 : CanariLength,                              
       _ self_y1 : CanariLength,                              
       _ self_x2 : CanariLength,                              
       _ self_y2 : CanariLength,                              
       _ self_cpx1 : CanariLength,                            
       _ self_cpy1 : CanariLength,                            
       _ self_cpx2 : CanariLength,                            
       _ self_cpy2 : CanariLength
) -> NSBezierPath {
//--- START OF USER ZONE 2
  let bp = NSBezierPath ()
  bp.move (to: NSPoint (x: self_x1, y: self_y1))
  bp.curve (
    to: NSPoint (x: self_x2, y: self_y2),
    controlPoint1: NSPoint (x: self_cpx1, y: self_cpy1),
    controlPoint2: NSPoint (x: self_cpx2, y: self_cpy2)
  )
  return bp
//--- END OF USER ZONE 2
}

//--------------------------------------------------------------------------------------------------
