//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Cocoa

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Cocoa

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

extension AutoLayoutProjectDocument {
  final func configure_addTrackButton (_ inOutlet : AutoLayoutDragSourceButton) {
//--- START OF USER ZONE 2
    inOutlet.register (
      draggedType: kDragAndDropBoardTrack,
      draggedObjectImage: { [weak self] in return self?.boardTrackImageFactory () },
      scaleProvider: self.boardObjectsController
    )
    inOutlet.image = NSImage (named: "track-in-board")
    inOutlet.imageScaling = .scaleProportionallyUpOrDown
  //--- Left Menu
    do {
      let menu = EBChoiceMenu ()
      menu.addItem (withTitle: "Any Angle", action: nil, keyEquivalent: "")
      menu.addItem (withTitle: "Octolinear (45°)", action: nil, keyEquivalent: "")
      menu.addItem (withTitle: "Rectilinear (90°)",  action: nil, keyEquivalent: "")
      menu.bind_selectedIndex (self.rootObject.mDirectionForNewTrack_property)
      inOutlet.mLeftContextualMenu = menu
    }
  //--- Right Menu
    let menu = EBChoiceMenu ()
    menu.addItem (withTitle: "Front Layer", action: nil, keyEquivalent: "")
    menu.addItem (withTitle: "Back Layer", action: nil, keyEquivalent: "")
    menu.addItem (withTitle: "Inner 1 Layer",  action: nil, keyEquivalent: "")
    menu.addItem (withTitle: "Inner 2 Layer",  action: nil, keyEquivalent: "")
    menu.addItem (withTitle: "Inner 3 Layer",  action: nil, keyEquivalent: "")
    menu.addItem (withTitle: "Inner 4 Layer",  action: nil, keyEquivalent: "")
    menu.bind_selectedIndex (self.rootObject.mBoardSideForNewTrack_property)
    inOutlet.mRightContextualMenu = menu
//--- END OF USER ZONE 2
  }
}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
