//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS GENERATED BY EASY BINDINGS, DO NOT MODIFY IT
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Cocoa

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//   EBView
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

extension EBView {

  //····················································································································

  func bind_underObjectsDisplay (_ model : EBReadOnlyProperty_EBShape, file : String, line : Int) {
    self.mUnderObjectsDisplayController = EBReadOnlyController_EBShape (
      model: model,
      callBack: { [weak self] in self?.updateUnderObjectsDisplay (from: model) }
    )
  }

  //····················································································································

  func unbind_underObjectsDisplay () {
    self.mUnderObjectsDisplayController?.unregister ()
    self.mUnderObjectsDisplayController = nil
  }

  //····················································································································

  private func updateUnderObjectsDisplay (from model : EBReadOnlyProperty_EBShape) {
    switch model.prop {
    case .empty, .multiple :
      self.mUnderObjectsDisplay = EBShape ()
    case .single (let v) :
      self.mUnderObjectsDisplay = v
    }
  }

  //····················································································································

}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
