//--- START OF USER ZONE 1


//--- END OF USER ZONE 1
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import AppKit

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

extension AutoLayoutDeviceDocument {
  @objc func performUnbindAllAction (_ inSender : NSObject?) {
//--- START OF USER ZONE 2
          for padProxy in self.rootObject.mPadProxies.values {
            padProxy.mIsNC = false
            padProxy.mPinInstance = nil
            padProxy.mPinInstanceName = ""
          }
//--- END OF USER ZONE 2
  }
}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
