//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS GENERATED BY EASY BINDINGS, DO NOT MODIFY IT
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import AppKit

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//    ReadOnlyObject_SymbolPinTypeInDevice
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

class ReadOnlyObject_SymbolPinTypeInDevice : ReadOnlyAbstractObjectProperty <SymbolPinTypeInDevice> {

  //····················································································································

  override func notifyModelDidChangeFrom (oldValue inOldValue : SymbolPinTypeInDevice?) {
    super.notifyModelDidChangeFrom (oldValue: inOldValue)
  //--- Remove observers from removed objects
    if let oldValue = inOldValue {
      oldValue.mPinX_property.stopsBeingObserved (by: self.mPinX_property) // Stored property
      oldValue.mPinY_property.stopsBeingObserved (by: self.mPinY_property) // Stored property
      oldValue.mXName_property.stopsBeingObserved (by: self.mXName_property) // Stored property
      oldValue.mYName_property.stopsBeingObserved (by: self.mYName_property) // Stored property
      oldValue.mName_property.stopsBeingObserved (by: self.mName_property) // Stored property
      oldValue.mNameHorizontalAlignment_property.stopsBeingObserved (by: self.mNameHorizontalAlignment_property) // Stored property
      oldValue.mPinNameIsDisplayedInSchematics_property.stopsBeingObserved (by: self.mPinNameIsDisplayedInSchematics_property) // Stored property
      oldValue.mXNumber_property.stopsBeingObserved (by: self.mXNumber_property) // Stored property
      oldValue.mYNumber_property.stopsBeingObserved (by: self.mYNumber_property) // Stored property
      oldValue.mNumberHorizontalAlignment_property.stopsBeingObserved (by: self.mNumberHorizontalAlignment_property) // Stored property
      oldValue.nameShape_property.stopsBeingObserved (by: self.nameShape_property) // Transient property
      if let relay = self.mObserversOf_mInstances { // to Many
        oldValue.mInstances_property.stopsBeingObserved (by: relay)
      }
    }
  //--- Add observers to added objects
    if let newValue = self.mWeakInternalValue {
      newValue.mPinX_property.startsToBeObserved (by: self.mPinX_property) // Stored property
      newValue.mPinY_property.startsToBeObserved (by: self.mPinY_property) // Stored property
      newValue.mXName_property.startsToBeObserved (by: self.mXName_property) // Stored property
      newValue.mYName_property.startsToBeObserved (by: self.mYName_property) // Stored property
      newValue.mName_property.startsToBeObserved (by: self.mName_property) // Stored property
      newValue.mNameHorizontalAlignment_property.startsToBeObserved (by: self.mNameHorizontalAlignment_property) // Stored property
      newValue.mPinNameIsDisplayedInSchematics_property.startsToBeObserved (by: self.mPinNameIsDisplayedInSchematics_property) // Stored property
      newValue.mXNumber_property.startsToBeObserved (by: self.mXNumber_property) // Stored property
      newValue.mYNumber_property.startsToBeObserved (by: self.mYNumber_property) // Stored property
      newValue.mNumberHorizontalAlignment_property.startsToBeObserved (by: self.mNumberHorizontalAlignment_property) // Stored property
      newValue.nameShape_property.startsToBeObserved (by: self.nameShape_property) // Transient property
      if let relay = self.mObserversOf_mInstances { // to Many
        newValue.mInstances_property.startsToBeObserved (by: relay)
      }
    }
  }

  //····················································································································
  //   Observers of 'mPinX' stored property
  //····················································································································

  final let mPinX_property = EBTransientProperty <Int?> ()

  //····················································································································
  //   Observers of 'mPinY' stored property
  //····················································································································

  final let mPinY_property = EBTransientProperty <Int?> ()

  //····················································································································
  //   Observers of 'mXName' stored property
  //····················································································································

  final let mXName_property = EBTransientProperty <Int?> ()

  //····················································································································
  //   Observers of 'mYName' stored property
  //····················································································································

  final let mYName_property = EBTransientProperty <Int?> ()

  //····················································································································
  //   Observers of 'mName' stored property
  //····················································································································

  final let mName_property = EBTransientProperty <String?> ()

  //····················································································································
  //   Observers of 'mNameHorizontalAlignment' stored property
  //····················································································································

  final let mNameHorizontalAlignment_property = EBTransientProperty <HorizontalAlignment?> ()

  //····················································································································
  //   Observers of 'mPinNameIsDisplayedInSchematics' stored property
  //····················································································································

  final let mPinNameIsDisplayedInSchematics_property = EBTransientProperty <Bool?> ()

  //····················································································································
  //   Observers of 'mXNumber' stored property
  //····················································································································

  final let mXNumber_property = EBTransientProperty <Int?> ()

  //····················································································································
  //   Observers of 'mYNumber' stored property
  //····················································································································

  final let mYNumber_property = EBTransientProperty <Int?> ()

  //····················································································································
  //   Observers of 'mNumberHorizontalAlignment' stored property
  //····················································································································

  final let mNumberHorizontalAlignment_property = EBTransientProperty <HorizontalAlignment?> ()

  //····················································································································
  //   Observers of 'nameShape' transient property
  //····················································································································

  final let nameShape_property = EBTransientProperty <EBShape?> ()

  //····················································································································
  //   Observable toMany property: mInstances
  //····················································································································

  private final var mObserversOf_mInstances : EBObservedObserver? = nil

  //····················································································································

  final func toMany_mInstances_StartsToBeObserved (by inObserver : EBObserverProtocol) {
    let relay : EBObservedObserver
    if let r = self.mObserversOf_mInstances {
      relay = r
    }else{
      relay = EBObservedObserver ()
      self.mWeakInternalValue?.mInstances_property.startsToBeObserved (by: relay)
      self.mObserversOf_mInstances = relay
    }
    relay.startsToBeObserved (by: inObserver)
  }

  //····················································································································

  final func toMany_mInstances_StopsBeingObserved (by inObserver : EBObserverProtocol) {
    self.mObserversOf_mInstances?.stopsBeingObserved (by: inObserver)
  }

  //····················································································································
  //   INIT
  //····················································································································

  override init () {
    super.init ()
  //--- Configure mPinX simple stored property
    self.mPinX_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mPinX_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mPinY simple stored property
    self.mPinY_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mPinY_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mXName simple stored property
    self.mXName_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mXName_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mYName simple stored property
    self.mYName_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mYName_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mName simple stored property
    self.mName_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mName_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mNameHorizontalAlignment simple stored property
    self.mNameHorizontalAlignment_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mNameHorizontalAlignment_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mPinNameIsDisplayedInSchematics simple stored property
    self.mPinNameIsDisplayedInSchematics_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mPinNameIsDisplayedInSchematics_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mXNumber simple stored property
    self.mXNumber_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mXNumber_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mYNumber simple stored property
    self.mYNumber_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mYNumber_property.optionalSelection ?? .single (nil)
    }
  //--- Configure mNumberHorizontalAlignment simple stored property
    self.mNumberHorizontalAlignment_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.mNumberHorizontalAlignment_property.optionalSelection ?? .single (nil)
    }
  //--- Configure nameShape transient property
    self.nameShape_property.mReadModelFunction = { [weak self] in
      return self?.mWeakInternalValue?.nameShape_property.optionalSelection ?? .single (nil)
    }
  }

  //····················································································································

}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//    StoredObject_SymbolPinTypeInDevice
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

final class StoredObject_SymbolPinTypeInDevice : ReadOnlyObject_SymbolPinTypeInDevice, EBSignatureObserverProtocol, DocumentStorablePropertyAndRelationshipProtocol {

 //····················································································································

  init (usedForSignature inUsedForSignature : Bool, strongRef inStrongReference : Bool, key inKey : String?) {
    self.mUsedForSignature = inUsedForSignature
    self.mIsStrongReference = inStrongReference
    self.mKey = inKey
    super.init ()
  }

  //····················································································································

  private let mKey : String?
  var key : String? { return self.mKey }
  
  //····················································································································

  func initialize (fromDictionary inDictionary : [String : Any],
                   managedObjectArray inManagedObjectArray : [EBManagedObject]) {
    if let key = self.mKey, let objectSavingIndex = inDictionary [key] as? Int {
      let object = inManagedObjectArray [objectSavingIndex] as! SymbolPinTypeInDevice
      self.setProp (object)
    }
  }

  //····················································································································

  func initialize (fromRange inRange : NSRange, ofData inData : Data, _ inRawObjectArray : [RawObject]) {
    if let idx = inData.base62EncodedInt (range: inRange) {
      let object = inRawObjectArray [idx].object as! SymbolPinTypeInDevice
      self.setProp (object)
    }
  }

  //····················································································································

  func store (inDictionary ioDictionary : inout [String : Any]) {
    if let key = self.mKey, let idx = self.mWeakInternalValue?.savingIndex {
      ioDictionary [key] = idx
    }
  }

  //····················································································································

  func enterRelationshipObjects (intoArray ioArray : inout [EBManagedObject]) {
    if self.mKey != nil, let object = self.mWeakInternalValue {
      ioArray.append (object)
    }
  }

  //····················································································································

  func appendValueTo (data ioData : inout Data) {
    if let object = self.propval {
      ioData.append (base62Encoded: object.savingIndex)
    }
  }

  //····················································································································
  //   Signature ?
  //····················································································································

  private let mUsedForSignature : Bool

  //····················································································································
  //   Undo manager
  //····················································································································

  weak var undoManager : UndoManager? = nil // SOULD BE WEAK

  //····················································································································
  //   Opposite relationship management
  //····················································································································

  private var mSetOppositeRelationship : Optional < (_ inManagedObject : SymbolPinTypeInDevice) -> Void > = nil
  private var mResetOppositeRelationship : Optional < (_ inManagedObject : SymbolPinTypeInDevice) -> Void > = nil

  //····················································································································

  func setOppositeRelationShipFunctions (setter inSetter : @escaping (_ inManagedObject : SymbolPinTypeInDevice) -> Void,
                                         resetter inResetter : @escaping (_ inManagedObject : SymbolPinTypeInDevice) -> Void) {
    self.mSetOppositeRelationship = inSetter
    self.mResetOppositeRelationship = inResetter
  }

  //····················································································································
  // Model will change
  //····················································································································

  override func notifyModelDidChangeFrom (oldValue inOldValue : SymbolPinTypeInDevice?) {
  //--- Register old value in undo manager
    self.undoManager?.registerUndo (withTarget: self) { $0.mWeakInternalValue = inOldValue }
  //---
    if let object = inOldValue {
      if self.mUsedForSignature {
        object.setSignatureObserver (observer: nil)
      }
      self.mResetOppositeRelationship? (object)
    }
  //---
    if let object = self.mWeakInternalValue {
      if self.mUsedForSignature {
        object.setSignatureObserver (observer: self)
      }
      self.mSetOppositeRelationship? (object)
    }
  //---
    super.notifyModelDidChangeFrom (oldValue: inOldValue)
  }

  //····················································································································
  // Model did change
  //····················································································································

  override func notifyModelDidChange () {
  //--- Notify observers
    self.observedObjectDidChange ()
    self.clearSignatureCache ()
  //---
    super.notifyModelDidChange ()
  }

  //····················································································································

  override var selection : EBSelection < SymbolPinTypeInDevice? > {
    if let object = self.mWeakInternalValue {
      return .single (object)
    }else{
      return .empty
    }
  }

  //····················································································································

  override var propval : SymbolPinTypeInDevice? { return self.mWeakInternalValue }

  //····················································································································
  //   setProp
  //····················································································································

  private let mIsStrongReference : Bool
  private var mStrongInternalValue : EBManagedObject? = nil // Only used for retaining

  //····················································································································

  func setProp (_ inValue : SymbolPinTypeInDevice?) {
    self.mWeakInternalValue = inValue
    if self.mIsStrongReference {
      self.mStrongInternalValue = inValue
    }
  }

  //····················································································································
  //   signature
  //····················································································································

  private weak var mSignatureObserver : EBSignatureObserverProtocol? = nil // SOULD BE WEAK

  //····················································································································

  private var mSignatureCache : UInt32? = nil

  //····················································································································

  func setSignatureObserver (observer inObserver : EBSignatureObserverProtocol?) {
    self.mSignatureObserver?.clearSignatureCache ()
    self.mSignatureObserver = inObserver
    inObserver?.clearSignatureCache ()
    self.clearSignatureCache ()
  }

  //····················································································································

  func signature () -> UInt32 {
    let computedSignature : UInt32
    if let s = self.mSignatureCache {
      computedSignature = s
    }else{
      computedSignature = self.computeSignature ()
      self.mSignatureCache = computedSignature
    }
    return computedSignature
  }

  //····················································································································

  final private func computeSignature () -> UInt32 {
    var crc : UInt32 = 0
    if let object = self.mWeakInternalValue {
      crc.accumulate (u32: object.signature ())
    }
    return crc
  }

  //····················································································································

  func clearSignatureCache () {
    if self.mSignatureCache != nil {
      self.mSignatureCache = nil
      self.mSignatureObserver?.clearSignatureCache ()
    }
  }

  //····················································································································

}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

