//----------------------------------------------------------------------------------------------------------------------
//  THIS FILE IS GENERATED BY EASY BINDINGS, DO NOT MODIFY IT
//----------------------------------------------------------------------------------------------------------------------

import Cocoa

//----------------------------------------------------------------------------------------------------------------------
//    ReadOnlyObject_SymbolTypeInDevice 
//----------------------------------------------------------------------------------------------------------------------

class ReadOnlyObject_SymbolTypeInDevice : ReadOnlyAbstractObjectProperty <SymbolTypeInDevice> {

  //····················································································································

  internal override func notifyModelDidChangeFrom (oldValue inOldValue : SymbolTypeInDevice?) {
    super.notifyModelDidChangeFrom (oldValue: inOldValue)
  //--- Remove observers from removed objects
    inOldValue?.mTypeName_property.removeEBObserver (self.mTypeName_property) // Stored property
    inOldValue?.mVersion_property.removeEBObserver (self.mVersion_property) // Stored property
    inOldValue?.mFileData_property.removeEBObserver (self.mFileData_property) // Stored property
    inOldValue?.mStrokeBezierPath_property.removeEBObserver (self.mStrokeBezierPath_property) // Stored property
    inOldValue?.mFilledBezierPath_property.removeEBObserver (self.mFilledBezierPath_property) // Stored property
    inOldValue?.versionString_property.removeEBObserver (self.versionString_property) // Transient property
    inOldValue?.instanceCount_property.removeEBObserver (self.instanceCount_property) // Transient property
    inOldValue?.documentSizeString_property.removeEBObserver (self.documentSizeString_property) // Transient property
    inOldValue?.pinNameShape_property.removeEBObserver (self.pinNameShape_property) // Transient property
  //--- Add observers to added objects
    self.mInternalValue?.mTypeName_property.addEBObserver (self.mTypeName_property) // Stored property
    self.mInternalValue?.mVersion_property.addEBObserver (self.mVersion_property) // Stored property
    self.mInternalValue?.mFileData_property.addEBObserver (self.mFileData_property) // Stored property
    self.mInternalValue?.mStrokeBezierPath_property.addEBObserver (self.mStrokeBezierPath_property) // Stored property
    self.mInternalValue?.mFilledBezierPath_property.addEBObserver (self.mFilledBezierPath_property) // Stored property
    self.mInternalValue?.versionString_property.addEBObserver (self.versionString_property) // Transient property
    self.mInternalValue?.instanceCount_property.addEBObserver (self.instanceCount_property) // Transient property
    self.mInternalValue?.documentSizeString_property.addEBObserver (self.documentSizeString_property) // Transient property
    self.mInternalValue?.pinNameShape_property.addEBObserver (self.pinNameShape_property) // Transient property
  }

  //····················································································································
  //   init
  //····················································································································

  override init () {
    super.init ()
    self.mTypeName_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.mTypeName_property.prop ?? .empty }
    self.mTypeName_property.mWriteModelFunction = { [weak self] (inValue : String) in self?.mInternalValue?.mTypeName_property.setProp (inValue) }
    self.mVersion_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.mVersion_property.prop ?? .empty }
    self.mVersion_property.mWriteModelFunction = { [weak self] (inValue : Int) in self?.mInternalValue?.mVersion_property.setProp (inValue) }
    self.mFileData_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.mFileData_property.prop ?? .empty }
    self.mFileData_property.mWriteModelFunction = { [weak self] (inValue : Data) in self?.mInternalValue?.mFileData_property.setProp (inValue) }
    self.mStrokeBezierPath_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.mStrokeBezierPath_property.prop ?? .empty }
    self.mStrokeBezierPath_property.mWriteModelFunction = { [weak self] (inValue : NSBezierPath) in self?.mInternalValue?.mStrokeBezierPath_property.setProp (inValue) }
    self.mFilledBezierPath_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.mFilledBezierPath_property.prop ?? .empty }
    self.mFilledBezierPath_property.mWriteModelFunction = { [weak self] (inValue : NSBezierPath) in self?.mInternalValue?.mFilledBezierPath_property.setProp (inValue) }
    self.versionString_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.versionString_property.prop ?? .empty }
    self.instanceCount_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.instanceCount_property.prop ?? .empty }
    self.documentSizeString_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.documentSizeString_property.prop ?? .empty }
    self.pinNameShape_property.mReadModelFunction = { [weak self] in self?.mInternalValue?.pinNameShape_property.prop ?? .empty }
  }

  //····················································································································
  //   Proxy of 'mTypeName' stored property
  //····················································································································

  let mTypeName_property = EBPropertyProxy_String ()

  var mTypeName_property_selection : EBSelection <String> {
    switch (self.mTypeName_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Proxy of 'mVersion' stored property
  //····················································································································

  let mVersion_property = EBPropertyProxy_Int ()

  var mVersion_property_selection : EBSelection <Int> {
    switch (self.mVersion_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Proxy of 'mFileData' stored property
  //····················································································································

  let mFileData_property = EBPropertyProxy_Data ()

  var mFileData_property_selection : EBSelection <Data> {
    switch (self.mFileData_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Proxy of 'mStrokeBezierPath' stored property
  //····················································································································

  let mStrokeBezierPath_property = EBPropertyProxy_NSBezierPath ()

  var mStrokeBezierPath_property_selection : EBSelection <NSBezierPath> {
    switch (self.mStrokeBezierPath_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Proxy of 'mFilledBezierPath' stored property
  //····················································································································

  let mFilledBezierPath_property = EBPropertyProxy_NSBezierPath ()

  var mFilledBezierPath_property_selection : EBSelection <NSBezierPath> {
    switch (self.mFilledBezierPath_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Observer of 'versionString' transient property
  //····················································································································

  let versionString_property = EBTransientProperty_String ()

  var versionString_property_selection : EBSelection <String> {
    switch (self.versionString_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Observer of 'instanceCount' transient property
  //····················································································································

  let instanceCount_property = EBTransientProperty_Int ()

  var instanceCount_property_selection : EBSelection <Int> {
    switch (self.instanceCount_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Observer of 'documentSizeString' transient property
  //····················································································································

  let documentSizeString_property = EBTransientProperty_String ()

  var documentSizeString_property_selection : EBSelection <String> {
    switch (self.documentSizeString_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Observer of 'pinNameShape' transient property
  //····················································································································

  let pinNameShape_property = EBTransientProperty_EBShape ()

  var pinNameShape_property_selection : EBSelection <EBShape> {
    switch (self.pinNameShape_property.prop) {
    case .empty :
      return .empty
    case .multiple :
      return .multiple
    case .single (let v) :
      return .single (v)
    }
  }

  //····················································································································
  //   Observable toMany property: mInstances
  //····················································································································

  private var mObserversOf_mInstances = EBWeakEventSet ()

  //····················································································································

  var mInstances_property_selection : EBSelection <[SymbolInstanceInDevice]> {
    if let model = self.propval {
      switch (model.mInstances_property_selection) {
      case .empty :
        return .empty
      case .multiple :
        return .multiple
      case .single (let v) :
        return .single (v)
      }
    }else{
      return .empty
    }
  }

  //····················································································································

  final func addEBObserverOf_mInstances (_ inObserver : EBEvent) {
    self.mObserversOf_mInstances.insert (inObserver)
    if let object = self.propval {
      object.mInstances_property.addEBObserver (inObserver)
    }
  }

  //····················································································································

  final func removeEBObserverOf_mInstances (_ inObserver : EBEvent) {
    self.mObserversOf_mInstances.remove (inObserver)
    if let object = self.propval {
      object.mInstances_property.removeEBObserver (inObserver)
    }
  }

  //····················································································································
  //   Observable toMany property: mPinTypes
  //····················································································································

  private var mObserversOf_mPinTypes = EBWeakEventSet ()

  //····················································································································

  var mPinTypes_property_selection : EBSelection <[SymbolPinTypeInDevice]> {
    if let model = self.propval {
      switch (model.mPinTypes_property_selection) {
      case .empty :
        return .empty
      case .multiple :
        return .multiple
      case .single (let v) :
        return .single (v)
      }
    }else{
      return .empty
    }
  }

  //····················································································································

  final func addEBObserverOf_mPinTypes (_ inObserver : EBEvent) {
    self.mObserversOf_mPinTypes.insert (inObserver)
    if let object = self.propval {
      object.mPinTypes_property.addEBObserver (inObserver)
    }
  }

  //····················································································································

  final func removeEBObserverOf_mPinTypes (_ inObserver : EBEvent) {
    self.mObserversOf_mPinTypes.remove (inObserver)
    if let object = self.propval {
      object.mPinTypes_property.removeEBObserver (inObserver)
    }
  }

  //····················································································································

}

//----------------------------------------------------------------------------------------------------------------------
//    TransientObject SymbolTypeInDevice
//----------------------------------------------------------------------------------------------------------------------

class TransientObject_SymbolTypeInDevice : ReadOnlyObject_SymbolTypeInDevice {

  //····················································································································
  //   Data provider
  //····················································································································

  private var mDataProvider : ReadOnlyObject_SymbolTypeInDevice? = nil
  private var mTransientKind : PropertyKind = .empty

  //····················································································································

  func setDataProvider (_ inProvider : ReadOnlyObject_SymbolTypeInDevice?) {
    if self.mDataProvider !== inProvider {
      self.mDataProvider?.detachClient (self)
      self.mDataProvider = inProvider
      self.mDataProvider?.attachClient (self)
    }
  }

  //····················································································································

  override func notifyModelDidChange () {
    let newObject : SymbolTypeInDevice? 
    if let dataProvider = self.mDataProvider {
      switch dataProvider.prop {
      case .empty :
        newObject = nil
        self.mTransientKind = .empty
      case .single (let v) :
        newObject = v
        self.mTransientKind = .single
       case .multiple :
        newObject = nil
        self.mTransientKind = .empty
      }
    }else{
      newObject = nil
      self.mTransientKind = .empty
    }
    self.mInternalValue = newObject
    super.notifyModelDidChange ()
  }

  //····················································································································

  override var prop : EBSelection < SymbolTypeInDevice? > {
    switch self.mTransientKind {
    case .empty :
      return .empty
    case .single :
      if let internalValue = self.mInternalValue {
        return .single (internalValue)
      }else{
        return .empty
      }
    case .multiple :
      return .multiple
    }
  }

  //····················································································································

  override var propval : SymbolTypeInDevice? { return self.mInternalValue }

  //····················································································································

}

//----------------------------------------------------------------------------------------------------------------------
//    ReadWriteObject_SymbolTypeInDevice
//----------------------------------------------------------------------------------------------------------------------

class ReadWriteObject_SymbolTypeInDevice : ReadOnlyObject_SymbolTypeInDevice {

  //····················································································································
 
  func setProp (_ inValue : SymbolTypeInDevice?) { } // Abstract method
  
  //····················································································································

}

//----------------------------------------------------------------------------------------------------------------------
//    Proxy: ProxyObject_SymbolTypeInDevice
//----------------------------------------------------------------------------------------------------------------------

final class ProxyObject_SymbolTypeInDevice : ReadWriteObject_SymbolTypeInDevice {

  //····················································································································

  private var mModel : ReadWriteObject_SymbolTypeInDevice? = nil

  //····················································································································

  func setModel (_ inModel : ReadWriteObject_SymbolTypeInDevice?) {
    if self.mModel !== inModel {
      self.mModel?.detachClient (self)
      self.mModel = inModel
      self.mModel?.attachClient (self)
    }
  }

  //····················································································································

  override func notifyModelDidChange () {
    let newModel : SymbolTypeInDevice?
    if let model = self.mModel {
      switch model.prop {
      case .empty :
        newModel = nil
      case .single (let v) :
        newModel = v
       case .multiple :
        newModel = nil
      }
    }else{
      newModel = nil
    }
    self.mInternalValue = newModel
    super.notifyModelDidChange ()
  }

  //····················································································································

  override func setProp (_ inValue : SymbolTypeInDevice?) {
    self.mModel?.setProp (inValue)
  }

  //····················································································································

  override var prop : EBSelection < SymbolTypeInDevice? > {
    if let model = self.mModel {
      return model.prop
    }else{
      return .empty
    }
  }

  //····················································································································

  override var propval : SymbolTypeInDevice? {
    if let model = self.mModel {
      switch model.prop {
      case .empty, .multiple :
        return nil
      case .single (let v) :
        return v
      }
    }else{
      return nil
    }
  }

  //····················································································································

}

//----------------------------------------------------------------------------------------------------------------------
//    StoredObject_SymbolTypeInDevice 
//----------------------------------------------------------------------------------------------------------------------

final class StoredObject_SymbolTypeInDevice : ReadWriteObject_SymbolTypeInDevice, EBSignatureObserverProtocol, EBObservableObjectProtocol {

 //····················································································································

  init (usedForSignature inUsedForSignature : Bool) {
    mUsedForSignature = inUsedForSignature
    super.init ()
  }

  //····················································································································
  //   Signature ?
  //····················································································································

  private let mUsedForSignature : Bool
  
  //····················································································································
  //   Undo manager
  //····················································································································

  weak var ebUndoManager : EBUndoManager? = nil // SOULD BE WEAK

 //····················································································································
  //   Opposite relationship management
  //····················································································································

  private var mSetOppositeRelationship : Optional < (_ inManagedObject : SymbolTypeInDevice) -> Void > = nil
  private var mResetOppositeRelationship : Optional < (_ inManagedObject : SymbolTypeInDevice) -> Void > = nil

  //····················································································································

  func setOppositeRelationShipFunctions (setter inSetter : @escaping (_ inManagedObject : SymbolTypeInDevice) -> Void,
                                         resetter inResetter : @escaping (_ inManagedObject : SymbolTypeInDevice) -> Void) {
    self.mSetOppositeRelationship = inSetter
    self.mResetOppositeRelationship = inResetter
  }
  
  //····················································································································

  var mValueExplorer : NSButton? {
    didSet {
      if let unwrappedExplorer = self.mValueExplorer {
        switch self.prop {
        case .empty, .multiple :
          break ;
        case .single (let v) :
          updateManagedObjectToOneRelationshipDisplay (object: v, button: unwrappedExplorer)
        }
      }
    }
  }

 //····················································································································
  // Model will change 
  //····················································································································

  override func notifyModelDidChangeFrom (oldValue inOldValue : SymbolTypeInDevice?) {
  //--- Register old value in undo manager
    self.ebUndoManager?.registerUndo (withTarget: self) { $0.mInternalValue = inOldValue }
  //---
    if let object = inOldValue {
      if self.mUsedForSignature {
        object.setSignatureObserver (observer: nil)
      }
      self.mResetOppositeRelationship? (object)
    }
  //---
    if let object = self.mInternalValue {
      if self.mUsedForSignature {
        object.setSignatureObserver (observer: self)
      }
      self.mSetOppositeRelationship? (object)
    }
  //---
    super.notifyModelDidChangeFrom (oldValue: inOldValue)
  }
 
  //····················································································································
  // Model did change 
  //····················································································································

  override func notifyModelDidChange () {
  //--- Update explorer
    if let valueExplorer = self.mValueExplorer {
      updateManagedObjectToOneRelationshipDisplay (object: self.mInternalValue, button: valueExplorer)
    }
  //--- Notify observers
    self.postEvent ()
    self.clearSignatureCache ()
  //---
    super.notifyModelDidChange ()
  }

  //····················································································································

  override var prop : EBSelection < SymbolTypeInDevice? > {
    if let object = self.mInternalValue {
      return .single (object)
    }else{
      return .empty
    }
  }

  //····················································································································

  override func setProp (_ inValue : SymbolTypeInDevice?) { self.mInternalValue = inValue }

  //····················································································································

  override var propval : SymbolTypeInDevice? { return self.mInternalValue }

  //····················································································································
  //   signature
  //····················································································································

  private weak var mSignatureObserver : EBSignatureObserverProtocol? = nil // SOULD BE WEAK

  //····················································································································

  private var mSignatureCache : UInt32? = nil

  //····················································································································

  final func setSignatureObserver (observer inObserver : EBSignatureObserverProtocol?) {
    self.mSignatureObserver?.clearSignatureCache ()
    self.mSignatureObserver = inObserver
    inObserver?.clearSignatureCache ()
    self.clearSignatureCache ()
  }

  //····················································································································

  final func signature () -> UInt32 {
    let computedSignature : UInt32
    if let s = self.mSignatureCache {
      computedSignature = s
    }else{
      computedSignature = self.computeSignature ()
      self.mSignatureCache = computedSignature
    }
    return computedSignature
  }
  
  //····················································································································

  final private func computeSignature () -> UInt32 {
    var crc : UInt32 = 0
    if let object = self.mInternalValue {
      crc.accumulateUInt32 (object.signature ())
    }
    return crc
  }

  //····················································································································

  final func clearSignatureCache () {
    if self.mSignatureCache != nil {
      self.mSignatureCache = nil
      self.mSignatureObserver?.clearSignatureCache ()
    }
  }

  //····················································································································
 
}

//----------------------------------------------------------------------------------------------------------------------

