//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Cocoa

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

func compute_BoardModelEntity_backPadsForDisplay (
       _ prefs_mergerDisplayBackPads : Bool,      
       _ self_backPads : MergerPadArray
) -> MergerPadArray {
//--- START OF USER ZONE 2
  return prefs_mergerDisplayBackPads ? self_backPads : MergerPadArray ([])
//--- END OF USER ZONE 2
}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
