//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
//  THIS FILE IS REGENERATED BY EASY BINDINGS, ONLY MODIFY IT WITHIN USER ZONES
//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

import Cocoa

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

@MainActor func transient_NetClassInProject_viaPadDiameter (
       _ self_mViaPadDiameter : Int,                        
       _ self_mViaPadDiameterUnit : Int
) -> String {
//--- START OF USER ZONE 2
       return stringFrom (valueInCanariUnit: self_mViaPadDiameter, displayUnit: self_mViaPadDiameterUnit)
//--- END OF USER ZONE 2
}

//——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
